### ISSUE TITLE
Version 4 - Material naming and parameters discussion

### ISSUE THREAD

**Issue by xelatihy** [xelatihy/yocto-gl#1171]
# Yocto Material

This issue tracks a discussion of materials naming and parameters.

There are four main concerns:
- material names
- what to do with emission 
- what to do with eta/ior
- what to do with volumetric properties

# Material Types

The current implementation supports the following materials:
- matte: Lambert brdf with `color` as diffuse
- metal: specular brdf with `color` as reflectivity at grazing angles (conductor fresnel for now) and `roughness`
- plastic: labert + specular with `color` as diffuse, `ior` and `roughness` for specular
- thinglass: thin transmission and reflection with `color` for transmission color and `ior` and `roughness` for specular/fresnel
- glass: same as before but with refraction and homogenous volume; volume uses `color` and `depth` for density and `scattering` and `anisotropy` for albedo
- metallic: glTF material with diffuse + specular, uses `color`, `metallic` and `roughness`
- subsurface: same as glass above with `scattering` texture and to allow a different way of entering the surface; it is ignored for now but I think it is better to keep a subsurface material for skin rendering
- volume: a purely volumetric material with bo surface interface, for now uses only the volumetric properties

# Material naming

Material naming is another complex issues. All renderers have different kind of nomenclature, so there is no common ground to use. There are three main variations for this

- names of common materials: matte, plastic, glass
    -  used in pbrt-v3
    - looks fine to me but gets confusing when we have glass for water or leaves from diffuse translucency
- names from physics: dielectric, conductor, coateddiffuse
    - usd in tungsten, pbrt-v4
    - to me it is not good
    - it implies that we support correctly physics behaviors 
    - it implies that you need to know physics to understand this, namely it scares people away
- names from phenomenological appearance: diffuse, reflective (metal), transmissive, refractive, translucent
   - used by nobody, but the one I prefer

I prefer the last naming convention.

# Material emission

Right now emission is kept as a separate property, just like in all renderers. This may or may not be a good idea.

- Pros: Simpler IO
- Pros: Other do it this way
- Pros: `color` is a color in [0,1], while `emission` is in [0,inf]; we could fix this by adding an `exposure` param
- Cons: can be confusing for new people looking for "lights"
- Cons: need more setup since we should not use a black BRDF by default, maybe
- Cons: 1 more param, 1 more texture
- Cons: cannot simulate funky behaviors, like coated emission (glow stick)
- Cons: less obvious where lights are (very minor)

Here I am not sure what to do.

# Material parameters

The following parameters are r mostly easonable, besides possibly coming up with better names.

- `color`: this is the main object reflectance, but it really is different in all materials; generally this is the one that gets the texture
    - called sometimes `reflectance` in pbrt-v4
    - I would probably leave it like this
    - `color_tex` for texture, but could be `color_map`
- `opacity`: clear what it is, I would leave it like this
    - alpha from `color_tex` 
- `roughness`: clear what it is, I would leave it like this
    - `roughness_tex` for texture, but could be `roughness_map`
- `metallic`: used only for glTF, I would leave it as is since it matches those specs
    - texture in `roughness_tex`
- `emission`: see above
    - `emission_tex` as texture
- `normal_tex` for normal maps; works like it ism but maybe call it `normal_map`

The more controversial parameters are `ior` and all volumetric settings.

For metals, we can use either Schlick's or conductors' Fresnel terms. I refer to introduce all the complexity of complex for frankly since we have no data and since it cannot be textured. So a simple `reflectivity` setting, as a color, works well enough.

For dielectrics it is harder. Right now we use `ior` for two things: coating/plastic and transmission/refraction. For coating, a reflectivity settings works fine and in fact is required in glTF. Before we used to have `specular` for that, but it was used in awkward ways, so it was changed to single `ior`. For transmission/refraction, `ior` is used in dielectric fresnel and refraction direction, but has two issues: (1) we do not do spectral rendering, so we need single value `ior`, and (2) nobody changes it since who knowns what it does.

WE can leave this as single `ior`, basically a read-only property. for now, I use dielectric Fresnel, but it is impossible to teach and explain (in fact all renders have the same cut&pasted code). I would not have a 3 channel `ior` since it is completely strange (see pbrt-v4 scenes). Th other option is to use `specular` set to {0.04, 0.04, 0.04} and be done with it (gt for when needed). In the future, that can be used for other effects, like colored coatings.

Not sure what to do here.

# Vometric properties

The other hard issue are volumetric properties. These are nasty since they are not intuitive no matter what one does. For this we have three materials now:
- glass: meant for refractive glass
- subsurface: meant for skin
- volume: meant for smoke and clouds, i.e. no interface

In the end, we need to set absorption, albedo and anisotropic (phase g), but it is helpful to consider the there cases separately.
 - glass: typically absorption only, so make sense that color control this, maybe
 - subsurface: need two set absorption but main color controls scattering, for example by using the Sony Parametrization to go from diffuse color to scattering
 - volume: need to control both absorption and scattering: main color from scattering, I am guessing (colored smoke?)
 
This already would suggest different parametrizations for at least glass and subsurface. Or maybe it make sense to keep the same one, which is what is done in production (glass: color -> density, subsurface: mfp -> density).

BTW, the renderer should also be changed based on these materials a bit. For example if no scattering is there, a simpler early exit is useful, but is for another day.

Here I am really not sure what do. Noe I know what to do with volumetric textures since I have not tried any data yet.

The bottom line is that we could follow two way:

- current paraterization:
    - color -> density
    - scattering -> albedo, probably named `subsurface`
- different parametrization for glass and subsurface where color sets different properties
    - glass though would remain as is now

I am not sure what to do.

**Comment by giacomonazzaro** [comment]
# Material naming
Naming materials based on the appearance is probably better idea for our goals.

- matte:
`matte` is ok. It communicates quite well the final appearance.

- metal:
`metal` is also ok, even though it does not describe the phenomenological appearance but rather the material. However metals have such a unique look that it is fine for this case.
 
- plastic:
This looks like the most common case and can model a wide range of real materials, far beyond plastic. For these reasons this is the most important and hardest material to name. I propose `glossy`, which should communicate a colored surface with reflections. It is quite generic, but it must be so.

- glass:
The word that people would use to describe both glass and water is `transparent`. I would exclude transmissive/refractive, they are still technical terms that describe the effect but not the appearance. 

- thinglass:
For the same reasons, I propose `transparent_thin`.

- subsurface: 
`subsurface` is ok, maybe `translucent` is better. My only worry is that someone can confuse it with the word with `transparent`.

- volume:
This should model gases, aerosols and particles like smoke, dust, fog, clouds, but none of these words is good. I guess `volume` is ok.

- metallic:
This is too similar to `metal`, having high potential to confuse people. Since we have it only to support Gltf, I would go for `gltf_metallic` which is intentionally ugly to warn the user and be clear about its usage. 

In the code there's also an unimplemented "leaf". I'm not sure about what it does, but a material with a reflective lobe and a in-place single-scattering lobe can be named `translucent_thin`.

To sum up:
`matte`, `glossy`, `metal`, `transparent`, `translucent`, `transparent_thin`,  `translucent_thin(?)`, `volume`, `gltf_metallic`.

# Material emission
We can keep emission as it is now, but we probably need to add `emissive` to the list of materials type.

# Material parameters
Material parameters and their naming are ok.

**Comment by xelatihy** [comment]
This should fine. When I have time I'll merge the changes back in.

**Comment by xelatihy** [comment]
Merged into #1151
