### ISSUE TITLE
No more 'trace_image_async_start'

### ISSUE THREAD

**Issue by guillaumechereau** [xelatihy/yocto-gl#596]
Not really an issue, more a question.

I noticed that some of the high level functions for async rendering have been removed, like 'trace_image_async_start'.  Is that going to be reintroduced, or should the client now handle this directly?  In a way I guess it does makes sense to keep the API low level.  I am just wondering if I should update to the new api now or wait a bit more.

Cheers.

**Comment by xelatihy** [comment]
Good question. The API for async was fine but only for the use case in itrace, since it mandated what concurrency library to use. For example, if you are using tbb or OpenMP thread pools, our work would add more threads.

So I decided to move all async behaviour in the application and expose instead the block API that is what is used internally. In fact, it is possible that we will eventually move all parallelism to the applications (right now, we have parallel bah build, scene loading and trace_samples/trace_image).

I think you can safely move to the new API. The code you are looking for is in yscnitrace. It is complex since we also support asynchronous editing.

If it becomes too much of an issue to move your code, I can re-introduce an async API. Let me know.

BTW, we are working on a change for refraction that might require a small material change if you use materials that are more complex than diffuse+specular.

**Comment by guillaumechereau** [comment]
OK thanks for the reply.

I agree that it is probably better to let the client handle the concurrency, to keep the API as simple as possible.  I'll try to have a look at how to port my code next week.

**Comment by xelatihy** [comment]
I'll close this since we are now API stable.
