### ISSUE TITLE
Error with metallic materials ?

### ISSUE THREAD

**Issue by guillaumechereau** [xelatihy/yocto-gl#598]
I think there is a bug in the BRDF evaluation of materials with metallic value:

      if (metallic) {
          point.specular = point.specular * (1 - metallic) + metallic * point.diffuse;
          point.diffuse  = metallic * point.diffuse * (1 - metallic);
      }

The multiplication by `metallic` in `point.diffuse` computation seems wrong: a material with a very little metallic factor value will have a diffuse value close to zero, while I would expect the opposite.  Or am I wrong?

**Comment by xelatihy** [comment]
This definition is correct since "diffuse" is the "base" color in glTF and Google filament definition. The reality is that it is best to just use diffuse and specular without ever using metallic. Let me explain better.

1. matte: diffuse == surface color, specular == 0
2. plastic: diffuse == surface color, specular == 0.04 (about)
3. metal: diffuse == 0, specular = surface color

Metallic is there to support game models but it is really just a hack, like it is in game engines.

We are considering a release with material that use an enum to indicate the material type, like matte, plastic, metal, glass, etc, both to speed things up and make it easier. It is not ready nor we know whether it is better than the ubershader approach we have now that is hard to modify and maintain.
If you have any feedback, let us know.

**Comment by guillaumechereau** [comment]
I will need to check a bit more.  I want to be able to render with the same materials as used by default by glTF2, so this is using metallic/roughness.  So far in my tests it only seems to work when I remove the 'metallic' factor.

**Comment by xelatihy** [comment]
Do you have a model we can use for testing in the glTF format?

**Comment by guillaumechereau** [comment]
I attach a glTF2 file generated with [tree.js online editor](https://threejs.org/editor/).  It uses a material with very low metallic value, and roughness = 0.5.  (I renamed the extension to txt from gltf so that github allow me to attach it here):
[scene.txt](https://github.com/xelatihy/yocto-gl/files/3436733/scene.txt)

A screenshot of the scene:
![image](https://user-images.githubusercontent.com/107679/61968058-9acf9380-b009-11e9-8864-e0d260d57f29.png)

And here is a screenshot of what I get in [goxel](https://goxel.xyz) with a similar material.  Top is the real time rendering, bottom is yocto (before my custom modification):
![bad](https://user-images.githubusercontent.com/107679/61968090-b8046200-b009-11e9-803d-70d9f29a40e0.png)

Also note that everything is fine when metallic is set to zero (since then point.diffuse is not changed, as expected).

Hope it clarifies the issue.

**Comment by xelatihy** [comment]
I am closing this for now since we are not supporting glTF for now due to time constraints.
